; sankey_function_initialize_colors.ahk
InitializeColors()
{
	global

	
	/*
	department_column	:= 4	; e.g. Transportation
	rdu_column 		:= 7 	; e.g. Marine Highway System
	component_column	:= 10	; e.g. Vessel Operations
	fund_column 		:= 11	; e.g. 1004 GF
	line_column		:= 12	; e.g. Expenditure/Reveneu
	group_column		:= 14	; e.g. UGF/DFG/FED/OTHER
	value_column		:= 16	; e.g. (value)
	*/
	
	
	; =CONCATENATE( "node_color_list[i].push({node_label: """, A2, """, node_color: ""rgb(120,120,120)""  	}) ;" )
	; =CONCATENATE( "node_color_list[i].push({node_label: """, A2, """, node_color: ""rgb(", RANDBETWEEN(-1,256), ",", RANDBETWEEN(-1,256), ",", RANDBETWEEN(-1,256), ")""  	}) ; )" )
	; =CONCATENATE( "link_color_list[i].push({node_label: """, A2, """, node_color: ""rgba(0,0,96,0.2)""  	}) ;" )
	
	;NODE COLORS
	node_color_list := []

	i = 1
	node_color_list[i] := []
	
	; SAME FOR ALL 
	node_color_list[i].push({node_label: "Expenditure"								    , node_color: "rgb(120,120,120)"  	}) ;
	node_color_list[i].push({node_label: "Permanent Part-Time"							, node_color: "rgb(120,120,120)"  	}) ;
	node_color_list[i].push({node_label: "Permanent Full-Time"							, node_color: "rgb(120,120,120)"  	}) ;
	node_color_list[i].push({node_label: "Non-Permanent"								, node_color: "rgb(120,120,120)"  	}) ;
	node_color_list[i].push({node_label: "Personal Services"						    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Travel"									    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Contractual Services"						    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Commodities"								    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Capital Outlay"							    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Line 7600"								    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Grants, Benefits"							    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Miscellaneous"								, node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Expenditure"								    , node_color: "rgb(120,120,120)"    }) ;
	node_color_list[i].push({node_label: "Position Count"								, node_color: "rgb(120,120,120)"    }) ;
	
	;DOM'S PREFERRED COLORS -DEPRECATED
	;node_color_list[i].push({node_label: "Designated General Funds"		, node_color: "rgb(243,240,114)"    }) ;
	;node_color_list[i].push({node_label: "Federal Funds"				, node_color: "rgb(34,144,216)"    	}) ;
	;node_color_list[i].push({node_label: "Other Funds"				, node_color: "rgb(149,79,255)"    	}) ;
	;node_color_list[i].push({node_label: "Undesignated General Funds"	, node_color: "rgb(231,0,0)"    	}) ;
	
	
	; OMB COLORS FROM FY21 BUDGET PRESENTATIONS
	;node_color_list[i].push({node_label: "Designated General Funds"		, node_color: "rgb(237,125,49)"    	}) ;
	;node_color_list[i].push({node_label: "Federal Funds"				, node_color: "rgb(255,192,0)"    		}) ;
	;node_color_list[i].push({node_label: "Other Funds"				, node_color: "rgb(166,166,166)"    	}) ;
	;node_color_list[i].push({node_label: "Unrestricted General Funds"	, node_color: "rgb(68,114,196)"    	}) ;
	
	; OMB COLORS FROM FY22 BUDGET PRESENTATIONS
	node_color_list[i].push({node_label: "Designated General Funds"		, node_color: "rgb(255,192,0)"    	}) ;
	node_color_list[i].push({node_label: "Federal Funds"				, node_color: "rgb(63,120,167)"    		}) ;
	node_color_list[i].push({node_label: "Other Funds"				, node_color: "rgb(165,165,165)"    	}) ;
	node_color_list[i].push({node_label: "Unrestricted General Funds"	, node_color: "rgb(68,114,196)"    	}) ;

; FROM EXCEL - DEPT NODES
node_color_list[i].push({node_label: "Administration", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Commerce", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Corrections", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Debt Service", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Educ & Early Devel", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Environ Conservation", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Fish & Game", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Fund Capitalization", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Fund Transfers", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Governor", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Health & Social Svcs", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Judiciary", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Labor & Workforce", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Law", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Legislature", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Military & Veterans Affairs", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Natural Resources", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Permanent Fund", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Public Safety", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Revenue", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Special Appropriations", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "State Retirement Payments", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "Transportation", node_color: "rgb(0,128,128)" }) 
node_color_list[i].push({node_label: "University of Alaska", node_color: "rgb(0,128,128)" }) 
	
; FROM EXCEL - RDU NODES
node_color_list[i].push({node_label: "Admin State Facilities Rent", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Alaska Public Offices Comm", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Centralized Admin. Services", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Division of Motor Vehicles", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Legal & Advocacy Services", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Office of IT", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Public Communications Services", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Risk Management", node_color: "rgb(145,62,225)" }) 
node_color_list[i].push({node_label: "Shared Services of Alaska", node_color: "rgb(71,16,162)" }) 
node_color_list[i].push({node_label: "AIDEA", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Ak Gasline Development", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "AK Oil & Gas Conservation Comm", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Alaska Energy Authority", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Alaska Seafood Marketing Inst", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Alcohol and Marijuana Control", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Banking and Securities", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Community and Regional Affairs", node_color: "rgb(145,62,225)" }) 
node_color_list[i].push({node_label: "Corp, Bus & Prof Licenses", node_color: "rgb(71,16,162)" }) 
node_color_list[i].push({node_label: "DCCED State Facilities Rent", node_color: "rgb(255,102,204)" }) 
node_color_list[i].push({node_label: "Economic Development", node_color: "rgb(102,255,204)" }) 
node_color_list[i].push({node_label: "Executive Admin and Dev", node_color: "rgb(0,176,240)" }) 
node_color_list[i].push({node_label: "Insurance", node_color: "rgb(204,153,0)" }) 
node_color_list[i].push({node_label: "Investments", node_color: "rgb(192,0,0)" }) 
node_color_list[i].push({node_label: "Reg Comm of Ak", node_color: "rgb(0,176,80)" }) 
node_color_list[i].push({node_label: "Revenue Sharing", node_color: "rgb(255,204,102)" }) 
node_color_list[i].push({node_label: "24 Hr Inst Utilities", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Administration and Support", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Facility-Cap Improvement Unit", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Health and Rehab Services", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Offender Habilitation", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Population Management", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Recidivism Reduction Grants", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Capital Projects(AS 42.45.065)", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "GO Bonds", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Lease Purchase Obligations", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Revenue Bonds", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "School Debt", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "AK LAM", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "AK Performance Scholarship Awd", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Alaska Council on the Arts", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Alaska Postsecondary Education", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Alaska Student Loan Corporation", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Commissions and Boards", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Education Support and Adm Svcs", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "K-12 Aid to School Districts", node_color: "rgb(145,62,225)" }) 
node_color_list[i].push({node_label: "K-12 Support", node_color: "rgb(71,16,162)" }) 
node_color_list[i].push({node_label: "Mt. Edgecumbe Boarding School", node_color: "rgb(255,102,204)" }) 
node_color_list[i].push({node_label: "State Facilities Maintenance", node_color: "rgb(102,255,204)" }) 
node_color_list[i].push({node_label: "Administration", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Air Quality", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "DEC Bldgs Maint & Operations", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Environmental Health", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Spill Prevention and Response", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Water", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Commercial Fisheries", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Habitat", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Sport Fisheries", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Statewide Support Services", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Subsistence Research & Monitori", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Wildlife Conservation", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Caps spent as duplicated funds", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Fund Caps (no approps out)", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "OpSys DGF Transfers (non-add)", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "OpSys Other Transfers (non-add)", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Commissions/Special Offices", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Elections", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Executive Operations", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Gov State Facilities Rent", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Office of Management & Budget", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "AK Psychiatric Institute", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Alaska Pioneer Homes", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Behavioral Health", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Children's Services", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Community Initiative Grants", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Departmental Support Services", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Health Care Services", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Human Svcs Comm Matching Grant", node_color: "rgb(145,62,225)" }) 
node_color_list[i].push({node_label: "Juvenile Justice", node_color: "rgb(71,16,162)" }) 
node_color_list[i].push({node_label: "Medicaid Svs", node_color: "rgb(255,102,204)" }) 
node_color_list[i].push({node_label: "Public Assistance", node_color: "rgb(102,255,204)" }) 
node_color_list[i].push({node_label: "Public Health", node_color: "rgb(0,176,240)" }) 
node_color_list[i].push({node_label: "Senior and Disabilities Svcs", node_color: "rgb(204,153,0)" }) 
node_color_list[i].push({node_label: "Senior Benefits Payment Program", node_color: "rgb(192,0,0)" }) 
node_color_list[i].push({node_label: "Alaska Court System", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Commission on Judicial Conduct", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Judicial Council", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Therapeutic Courts", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "AVTEC", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Commissioner and Administrative", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Employment & Training Svcs", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Labor Standards and Safety", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Vocational Rehabilitation", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Workers' Compensation", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Administration and Support", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Civil Division", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Criminal Division", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Legal Contracts ", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Budget and Audit Committee", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Legislative Council", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Legislative Operating Budget", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Alaska Aerospace Corp", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Military & Veterans Affairs", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Administration and Support", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Agriculture", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Fire Land and Water Resources", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Oil and Gas", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Parks and Outdoor Recreation", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Permanent Fund", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Permanent Fund Corpus", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "PF Inflation Proofing", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "AK Police Standards Council", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Alaska State Troopers", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Domestic Viol/Sexual Assault", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Fire and Life Safety", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Statewide Support", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Village Public Safety Officers", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Violent Crimes Comp Board", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Administration and Support", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "AK Municipal Bond Bank Auth", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "AK Permanent Fund Corporation", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Alaska Housing Finance Corp", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Child Support Services", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Mental Health Trust Authority", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "Taxation and Treasury", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Bonds for Tax Credit Purchases", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Comprehensive Insurance Program", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Shared Taxes", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "EPORS", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Judicial Retirement System", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "PERS State Assistance", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "TRS State Assistance", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Administration and Support", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Design, Engineering and Construction", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Facilities Services", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Highways, Aviation and Facilities", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "International Airports", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Marine Highway System", node_color: "rgb(0,127,212)" }) 
node_color_list[i].push({node_label: "State Equipment Fleet", node_color: "rgb(109,177,2)" }) 
node_color_list[i].push({node_label: "Budget Reductions/Additions", node_color: "rgb(182,161,255)" }) 
node_color_list[i].push({node_label: "Enterprise Entities", node_color: "rgb(255,255,5)" }) 
node_color_list[i].push({node_label: "Statewide Services", node_color: "rgb(255,96,6)" }) 
node_color_list[i].push({node_label: "Univ of Alaska Anchorage", node_color: "rgb(25,0,253)" }) 
node_color_list[i].push({node_label: "Univ of Alaska Fairbanks", node_color: "rgb(0,242,42)" }) 
node_color_list[i].push({node_label: "Univ of Alaska Southeast", node_color: "rgb(0,127,212)" }) 




; FROM EXCEL - FUND NODES
node_color_list[i].push({node_label: "1001 Constitutional Budget Reserve Fund", node_color: "rgb(231,0,0)" }) 
node_color_list[i].push({node_label: "1002 Federal Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1003 General Fund Match", node_color: "rgb(231,0,0)" }) 
node_color_list[i].push({node_label: "1004 General Fund Receipts", node_color: "rgb(231,0,0)" }) 
node_color_list[i].push({node_label: "1005 General Fund/Program Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1007 Interagency Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1013 Alcoholism & Drug Abuse Revolving Loan", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1014 Donated Commodity/Handling Fee Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1016 CSSD Federal Incentive Payments", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1017 Benefits Systems Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1018 Exxon Valdez Oil Spill Settlement", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1021 Agricultural Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1023 FICA Administration Fund Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1024 Fish and Game Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1026 Highways/Equipment Working Capital Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1027 International Airport Revenue Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1029 Public Employees Retirement System Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1030 School Fund (Cigarette Tax)", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1031 Second Injury Fund Reserve Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1032 Fishermen's Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1033 Surplus Property Revolving Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1034 Teachers Retirement System Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1036 Commercial Fishing Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1037 General Fund / Mental Health", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1040 Real Estate Surety Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1041 Permanent Fund Earnings Reserve Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1042 Judicial Retirement System", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1043 Impact Aid for K-12 Schools", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1045 National Guard & Naval Militia Retirement System", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1048 University Restricted Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1049 Training and Building Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1050 Permanent Fund Dividend Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1052 Oil/Hazardous Prevention/Response Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1054 State Employment & Training Program", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1055 Interagency/Oil & Hazardous Waste", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1061 Capital Improvement Project Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1062 Power Project Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1066 Public School Trust Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1070 Fisheries Enhancement Revolving Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1074 Bulk Fuel Revolving Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1075 Alaska Clean Water Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1076 Marine Highway System Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1081 Information Services Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1092 Mental Health Trust Authority Authorized Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1093 Clean Air Protection Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1094 Mental Health Trust Administration", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1100 Alaska Drinking Water Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1101 Alaska Aerospace Development Corporation Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1102 Alaska Industrial Development & Export Authority Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1103 Alaska Housing Finance Corporation Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1104 Alaska Municipal Bond Bank Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1105 Alaska Permanent Fund Corporation Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1106 Alaska Student Loan Corporation Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1107 Alaska Energy Authority Corporate Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1108 Statutory Designated Program Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1109 Test Fisheries Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1117 Randolph Sheppard Small Business Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1133 CSSD Administrative Cost Reimbursement", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1140 AIDEA Dividend", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1141 RCA Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1144 Clean Water Fund Bond Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1145 Art in Public Places Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1147 Public Building Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1151 Technical Vocational Education Program Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1153 State Land Disposal Income Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1154 Shore Fisheries Development Lease Program", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1155 Timber Sale Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1156 Receipt Supported Services", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1157 Workers Safety and Compensation Administration Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1159 Drinking Water Fund Bond Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1162 Alaska Oil & Gas Conservation Commission Rcpts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1164 Rural Development Initiative Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1166 Commercial Passenger Vessel Environmental Compliance Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1168 Tobacco Use Education and Cessation Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1169 PCE Endowment Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1170 Small Business Economic Development Revolving Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1171 PF Dividend Appropriations in lieu of Dividends to Criminals", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1172 Building Safety Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1173 Miscellaneous Earnings", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1174 UA Intra-Agency Transfers", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1179 Passenger Facility Charges", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1180 Alcohol & Other Drug Abuse Treatment & Prevention Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1181 Alaska Veterans' Memorial Endowment Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1184 General Obligation Bond Debt Service Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1185 Election Fund (HAVA)", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1192 Mine Reclamation Trust Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1198 Alaska Fish and Game Revenue Bond Redemption Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1199 Alaska Sport Fishing Enterprise Account", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1200 Vehicle Rental Tax Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1201 Commercial Fisheries Entry Commission Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1202 Anatomical Gift Awareness Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1203 Workers' Compensation Benefits Guaranty Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1205 Berth Fees for the Ocean Ranger Program", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1206 Commercial Passenger Vessel Tax", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1210 Renewable Energy Grant Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1212 Federal Stimulus: ARRA 2009", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1214 Whittier Tunnel Toll Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1215 Uniform Commercial Registration fees", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1216 Boat Registration Fees", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1217 NGF Earnings", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1221 Civil Legal Services Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1223 Commercial Charter Fisheries RLF", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1224 Mariculture Revolving Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1226 Alaska Higher Education Investment Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1227 Alaska Microloan Revolving Loan Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1230 Alaska Clean Water Administrative Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1231 Alaska Drinking Water Administrative Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1232 In-state Pipeline Fund Interagency", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1234 License Plates", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1235 Alaska Liquefied Natural Gas Project Fund (AGDC-LNG)", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1236 Alaska Liquefied Natural Gas Project Fund I/A (AK LNG I/A)", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1237 Vocational Rehabilitation Small Bus. Enterprise Revolving Fd", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1239 Aviation Fuel Tax Revenue", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1244 Rural Airport Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1245 Rural Airport Receipts I/A", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1246 Recidivism Reduction Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1247 Medicaid Monetary Recoveries", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1249 Motor Fuel Tax Receipts", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1254 Marijuana Education and Treatment Fund", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1261 Shared Taxes", node_color: "rgb(120,120,120)" }) 
node_color_list[i].push({node_label: "1262 Non-mandatory Royalty Deposits to the Permanent Fund", node_color: "rgb(120,120,120)" }) 

	; LINK COLORS
	link_color_list := []
	
	i = 1
	link_color_list[i] := []

	; SAME FOR ALL
	link_color_list[i].push({link_label: "Expenditure"								    , link_color: "rgba(0,0,96,0.2)"  			}) ;
	link_color_list[i].push({link_label: "Permanent Part-Time"							, link_color: "rgba(0,0,96,0.2)"  			}) ;
	link_color_list[i].push({link_label: "Permanent Full-Time"							, link_color: "rgba(0,0,96,0.2)"  			}) ;
	link_color_list[i].push({link_label: "Non-Permanent"								, link_color: "rgba(0,0,96,0.2)"  			}) ;
	
	; OMB Colors
	link_color_list[i].push({link_label: "Designated General Funds"						, link_color: "rgba(237,125,49,0.2)"    	}) ;
	link_color_list[i].push({link_label: "Federal Funds"								, link_color: "rgba(255,192,0,0.2)"    		}) ;
	link_color_list[i].push({link_label: "Other Funds"									, link_color: "rgba(166,166,166,0.2)"    	}) ;
	link_color_list[i].push({link_label: "Undesignated General Funds"					, link_color: "rgba(68,114,196,0.2)"    	}) ;
	
; FROM EXCEL - FUND LINKS
link_color_list[i].push({link_label: "1001 Constitutional Budget Reserve Fund", link_color: "rgba(255,0,0,0.2)" }) 
link_color_list[i].push({link_label: "1002 Federal Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1003 General Fund Match", link_color: "rgba(255,0,0,0.2)" }) 
link_color_list[i].push({link_label: "1004 General Fund Receipts", link_color: "rgba(255,0,0,0.2)" }) 
link_color_list[i].push({link_label: "1005 General Fund/Program Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1007 Interagency Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1013 Alcoholism & Drug Abuse Revolving Loan", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1014 Donated Commodity/Handling Fee Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1016 CSSD Federal Incentive Payments", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1017 Benefits Systems Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1018 Exxon Valdez Oil Spill Settlement", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1021 Agricultural Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1023 FICA Administration Fund Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1024 Fish and Game Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1026 Highways/Equipment Working Capital Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1027 International Airport Revenue Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1029 Public Employees Retirement System Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1030 School Fund (Cigarette Tax)", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1031 Second Injury Fund Reserve Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1032 Fishermen's Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1033 Surplus Property Revolving Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1034 Teachers Retirement System Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1036 Commercial Fishing Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1037 General Fund / Mental Health", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1040 Real Estate Surety Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1041 Permanent Fund Earnings Reserve Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1042 Judicial Retirement System", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1043 Impact Aid for K-12 Schools", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1045 National Guard & Naval Militia Retirement System", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1048 University Restricted Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1049 Training and Building Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1050 Permanent Fund Dividend Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1052 Oil/Hazardous Prevention/Response Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1054 State Employment & Training Program", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1055 Interagency/Oil & Hazardous Waste", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1061 Capital Improvement Project Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1062 Power Project Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1066 Public School Trust Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1070 Fisheries Enhancement Revolving Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1074 Bulk Fuel Revolving Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1075 Alaska Clean Water Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1076 Marine Highway System Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1081 Information Services Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1092 Mental Health Trust Authority Authorized Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1093 Clean Air Protection Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1094 Mental Health Trust Administration", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1100 Alaska Drinking Water Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1101 Alaska Aerospace Development Corporation Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1102 Alaska Industrial Development & Export Authority Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1103 Alaska Housing Finance Corporation Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1104 Alaska Municipal Bond Bank Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1105 Alaska Permanent Fund Corporation Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1106 Alaska Student Loan Corporation Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1107 Alaska Energy Authority Corporate Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1108 Statutory Designated Program Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1109 Test Fisheries Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1117 Randolph Sheppard Small Business Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1133 CSSD Administrative Cost Reimbursement", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1140 AIDEA Dividend", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1141 RCA Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1144 Clean Water Fund Bond Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1145 Art in Public Places Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1147 Public Building Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1151 Technical Vocational Education Program Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1153 State Land Disposal Income Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1154 Shore Fisheries Development Lease Program", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1155 Timber Sale Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1156 Receipt Supported Services", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1157 Workers Safety and Compensation Administration Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1159 Drinking Water Fund Bond Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1162 Alaska Oil & Gas Conservation Commission Rcpts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1164 Rural Development Initiative Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1166 Commercial Passenger Vessel Environmental Compliance Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1168 Tobacco Use Education and Cessation Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1169 PCE Endowment Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1170 Small Business Economic Development Revolving Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1171 PF Dividend Appropriations in lieu of Dividends to Criminals", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1172 Building Safety Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1173 Miscellaneous Earnings", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1174 UA Intra-Agency Transfers", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1179 Passenger Facility Charges", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1180 Alcohol & Other Drug Abuse Treatment & Prevention Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1181 Alaska Veterans' Memorial Endowment Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1184 General Obligation Bond Debt Service Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1185 Election Fund (HAVA)", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1192 Mine Reclamation Trust Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1198 Alaska Fish and Game Revenue Bond Redemption Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1199 Alaska Sport Fishing Enterprise Account", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1200 Vehicle Rental Tax Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1201 Commercial Fisheries Entry Commission Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1202 Anatomical Gift Awareness Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1203 Workers' Compensation Benefits Guaranty Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1205 Berth Fees for the Ocean Ranger Program", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1206 Commercial Passenger Vessel Tax", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1210 Renewable Energy Grant Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1212 Federal Stimulus: ARRA 2009", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1214 Whittier Tunnel Toll Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1215 Uniform Commercial Registration fees", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1216 Boat Registration Fees", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1217 NGF Earnings", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1221 Civil Legal Services Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1223 Commercial Charter Fisheries RLF", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1224 Mariculture Revolving Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1226 Alaska Higher Education Investment Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1227 Alaska Microloan Revolving Loan Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1230 Alaska Clean Water Administrative Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1231 Alaska Drinking Water Administrative Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1232 In-state Pipeline Fund Interagency", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1234 License Plates", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1235 Alaska Liquefied Natural Gas Project Fund (AGDC-LNG)", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1236 Alaska Liquefied Natural Gas Project Fund I/A (AK LNG I/A)", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1237 Vocational Rehabilitation Small Bus. Enterprise Revolving Fd", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1239 Aviation Fuel Tax Revenue", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1244 Rural Airport Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1245 Rural Airport Receipts I/A", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1246 Recidivism Reduction Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1247 Medicaid Monetary Recoveries", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1249 Motor Fuel Tax Receipts", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1254 Marijuana Education and Treatment Fund", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1261 Shared Taxes", link_color: "rgba(0,0,96,0.2)" }) 
link_color_list[i].push({link_label: "1262 Non-mandatory Royalty Deposits to the Permanent Fund", link_color: "rgba(0,0,96,0.2)" }) 


}
