


csv_find_replace_column( "Line 71000"       , "Personal Services"               , "REPORT_LINE" )
csv_find_replace_column( "Line 72000"       , "Travel"                          , "REPORT_LINE" )
csv_find_replace_column( "Line 73000"       , "Contractual Services"            , "REPORT_LINE" )
csv_find_replace_column( "Line 74000"       , "Commodities"                     , "REPORT_LINE" )
csv_find_replace_column( "Line 75000"       , "Capital Outlay"                  , "REPORT_LINE" )
csv_find_replace_column( "Line 76000"       , "Line 7600"                       , "REPORT_LINE" )
csv_find_replace_column( "Line 77000"       , "Grants, Benefits"                , "REPORT_LINE" )
csv_find_replace_column( "Line 78000"       , "Miscellaneous"                   , "REPORT_LINE" )
csv_find_replace_column( "PPT"              , "Permanent Part-Time"             , "REPORT_LINE" )
csv_find_replace_column( "PFT"              , "Permanent Full-Time"             , "REPORT_LINE" )
csv_find_replace_column( "NP"               , "Non-Permanent"                   , "REPORT_LINE" )

csv_find_replace_column( "DGF"              , "Designated General Funds"        , "FUND_GROUP")        
csv_find_replace_column( "UGF"              , "Unrestricted General Funds"      , "FUND_GROUP")
csv_find_replace_column( "Other"            , "Other Funds"                     , "FUND_GROUP")
csv_find_replace_column( "Fed"              , "Federal Funds"                   , "FUND_GROUP")

csv_find_replace_column( "Military & Veterans' Affairs",        "Military & Veterans Affairs",          "DEPT_NAME" )
csv_find_replace_column( "Fish and Game",                       "Fish & Game",                          "DEPT_NAME")

csv_find_replace_column( "Highways, Aviation and Faciliti",     "Highways, Aviation and Facilities",    "RDU_NAME" )
csv_find_replace_column( "Design, Engineering and Constru",     "Design, Engineering and Construction", "RDU_NAME" )


; Capital Department Name Cleanup for Fund Category, FIND -> REPLACE (replace with standardized ABS name, department_list.abs_name)
csv_find_replace_column( "Admin"												, "Administration"				, "DEPT_NAME" )
csv_find_replace_column( "Commerce"											, "Commerce"					, "DEPT_NAME" )
csv_find_replace_column( "EnvCon"												, "Environ Conservation"			, "DEPT_NAME" )
csv_find_replace_column( "Gov"												, "Governor"					, "DEPT_NAME" )
;csv_find_replace_column( "H&SS"												, "Health & Social Services"		, "DEPT_NAME" )
csv_find_replace_column( "DOH"												, "Health"					, "DEPT_NAME" )
csv_find_replace_column( "FCS"												, "Family & Community Services"	, "DEPT_NAME" )
csv_find_replace_column( "Labor"												, "Labor & Workforce"			, "DEPT_NAME" )
csv_find_replace_column( "M&VA"												, "Military & Veterans Affairs"	, "DEPT_NAME" )
csv_find_replace_column( "NatRes"												, "Natural Resources"			, "DEPT_NAME" )
csv_find_replace_column( "Rev"												, "Revenue"					, "DEPT_NAME" )
csv_find_replace_column( "Trans"												, "Transportation"				, "DEPT_NAME" )
csv_find_replace_column( "PubSaf"												, "Public Safety"				, "DEPT_NAME" )
csv_find_replace_column( "FishGm"												, "Fish & Game"				, "DEPT_NAME" )
csv_find_replace_column( "Courts"												, "Judiciary"					, "DEPT_NAME" )
csv_find_replace_column( "Correct"												, "Corrections"				, "DEPT_NAME" )
csv_find_replace_column( "E&ED"												, "Educ & Early Devel"			, "DEPT_NAME" )
csv_find_replace_column( "Univ"												, "University of Alaska"			, "DEPT_NAME" )

; Capital Cleanup for statewide, FIND -> REPLACE (replace with standardized ABS name, department_list.abs_name)
csv_find_replace_column( "Department of Administration"							, "Administration"				, "DEPT_NAME" )
csv_find_replace_column( "Department of Commerce, Community, and Economic Development"	, "Commerce"                       , "DEPT_NAME" )
csv_find_replace_column( "Department of Environmental Conservation"					, "Environ Conservation"           , "DEPT_NAME" )
csv_find_replace_column( "Office of the Governor"									, "Governor"                       , "DEPT_NAME" )
;csv_find_replace_column( "Department of Health & Social Services"					, "Health & Social Services"       , "DEPT_NAME" )
csv_find_replace_column( "Department of Health"									, "Health"					, "DEPT_NAME" )
csv_find_replace_column( "Department of Family and Community Services"				, "Family & Community Services"	, "DEPT_NAME" )
csv_find_replace_column( "Department of Labor and Workforce Development"				, "Labor & Workforce"              , "DEPT_NAME" )
csv_find_replace_column( "Department of Military and Veterans Affairs"				, "Military & Veterans Affairs"    , "DEPT_NAME" )
csv_find_replace_column( "Department of Natural Resources"							, "Natural Resources"              , "DEPT_NAME" )
csv_find_replace_column( "Department of Revenue"									, "Revenue"                        , "DEPT_NAME" )
csv_find_replace_column( "Department of Transportation/Public Facilities"				, "Transportation"                 , "DEPT_NAME" )
csv_find_replace_column( "Department of Public Safety"								, "Public Safety"                  , "DEPT_NAME" )
csv_find_replace_column( "Department of Fish and Game"								, "Fish & Game"                    , "DEPT_NAME" )
csv_find_replace_column( "Department of Corrections"								, "Corrections"                    , "DEPT_NAME" )
csv_find_replace_column( "Department of Education and Early Development"				, "Educ & Early Devel"             , "DEPT_NAME" )

; Capital Category Cleanup
csv_find_replace_column( "DGF_AMOUNT"       , "Designated General Funds"        , "FUND_GROUP")         ;DGF has to go first! Otherwise the line below matches.
csv_find_replace_column( "UGF_AMOUNT"       , "Unrestricted General Funds"      , "FUND_GROUP")
csv_find_replace_column( "O_AMOUNT"         , "Other Funds"                     , "FUND_GROUP")
csv_find_replace_column( "F_AMOUNT"         , "Federal Funds"                   , "FUND_GROUP")


; Capital Fund Cleanup
csv_find_replace_column("1230 AKCW Ad Fu","1230 Alaska Clean Water Administrative Fund", "REPORT_LINE")
csv_find_replace_column("1231 AKDW Ad Fu","1231 Alaska Drinking Water Administrative Fund", "REPORT_LINE")
csv_find_replace_column("1232 ISPF-I/A","1232 In-state Pipeline Fund Interagency", "REPORT_LINE")
csv_find_replace_column("1233 Muni Bonds","1233 Municipal Bond Bank Bonds", "REPORT_LINE")
csv_find_replace_column("1235 AGDC-LNG","1235 Alaska Liquefied Natural Gas Project Fund (AGDC-LNG)", "REPORT_LINE")
csv_find_replace_column("1236 AK LNG I/A","1236 Alaska Liquefied Natural Gas Project Fund I/A (AK LNG I/A)", "REPORT_LINE")
csv_find_replace_column("1238 VaccAssess","1238 Vaccine Assessment Account", "REPORT_LINE")
csv_find_replace_column("1237 VocSmBus","1237 Vocational Rehabilitation Small Bus. Enterprise Revolving Fd", "REPORT_LINE")
csv_find_replace_column("1241 GF/LNG","1241 General Fund/Liquefied Natural Gas", "REPORT_LINE")
csv_find_replace_column("1243 SBR","1243 Statutory Budget Reserve Fund", "REPORT_LINE")
csv_find_replace_column("1249 Motor Fuel","1249 Motor Fuel Tax Receipts", "REPORT_LINE")
csv_find_replace_column("1250 Maint Cap","1250 Maintenance and Capital Fund", "REPORT_LINE")
csv_find_replace_column("1253 STA Bonds","1253 Subject to Appropriation Bonds", "REPORT_LINE")
csv_find_replace_column("1254 MET Fund","1254 Marijuana Education and Treatment Fund", "REPORT_LINE")
csv_find_replace_column("1255 Invest","1255 Securities Investor Education and Training Fund", "REPORT_LINE")
csv_find_replace_column("1256 Ed Endow","1256 Education Endowment Fund", "REPORT_LINE")
csv_find_replace_column("1257 Div Raffle","1257 Dividend Raffle Fund", "REPORT_LINE")
csv_find_replace_column("1261 Shared Tax","1261 Shared Taxes", "REPORT_LINE")
csv_find_replace_column("1262 StatPFRoy","1262 Non-mandatory Royalty Deposits to the Permanent Fund", "REPORT_LINE")
csv_find_replace_column("1251 Non-UGF","1251 Non-UGF (Leg Fiscal Note System Only)", "REPORT_LINE")
csv_find_replace_column("1252 DGF Temp","1252 DGF Temp (Leg Fiscal Note System)", "REPORT_LINE")
csv_find_replace_column("1264 MET Alt","1264 MET Alt", "REPORT_LINE")
csv_find_replace_column("1265 COVID Fed","1265 Non-specific COVID Fed", "REPORT_LINE")
csv_find_replace_column("1268 MH Tr Res","1268 Mental Health Trust Reserve", "REPORT_LINE")
csv_find_replace_column("1267 FTA CRRSAA","1267 FTA CRRSAA Grant Funding", "REPORT_LINE")
csv_find_replace_column("1269 CSLFRF","1269 CSLFRF (Fed) Flexible ARP Funding", "REPORT_LINE")
csv_find_replace_column("1266 COVID UGF","1266 COVID UGF", "REPORT_LINE")
csv_find_replace_column("1270 FHWA CRRSA","1270 FHWA CRRSAA Fed", "REPORT_LINE")
csv_find_replace_column("1271 ARPA Rev R","1271 ARPA Revenue Replacement UGF", "REPORT_LINE")
csv_find_replace_column("1246 Recid Redu","1246 Recidivism Reduction Fund", "REPORT_LINE")
csv_find_replace_column("1247 Med Recov","1247 Medicaid Monetary Recoveries", "REPORT_LINE")
csv_find_replace_column("1248 ACHI Fund","1248 Alaska Comprehensive Health Insurance Fund", "REPORT_LINE")
csv_find_replace_column("1000 Restrtd GF","1000 Restricted General Fund", "REPORT_LINE")
csv_find_replace_column("1002 Fed Rcpts","1002 Federal Receipts", "REPORT_LINE")
csv_find_replace_column("1003 G/F Match","1003 General Fund Match", "REPORT_LINE")
csv_find_replace_column("1004 Gen Fund","1004 General Fund Receipts", "REPORT_LINE")
csv_find_replace_column("1005 GF/Prgm","1005 General Fund/Program Receipts", "REPORT_LINE")
csv_find_replace_column("1007 I/A Rcpts","1007 Interagency Receipts", "REPORT_LINE")
csv_find_replace_column("1010 UA/INT INC","1010 University of Alaska Interest Income", "REPORT_LINE")
csv_find_replace_column("1012 Rail Enrgy","1012 Railbelt Energy Fund", "REPORT_LINE")
csv_find_replace_column("1013 Alchl/Drug","1013 Alcoholism & Drug Abuse Revolving Loan", "REPORT_LINE")
csv_find_replace_column("1014 Donat Comm","1014 Donated Commodity/Handling Fee Account", "REPORT_LINE")
csv_find_replace_column("1015 UA/DFA SVC","1015 U/A Dormitory/Food/Auxiliary Service", "REPORT_LINE")
csv_find_replace_column("1016 Fed Incent","1016 CSSD Federal Incentive Payments", "REPORT_LINE")
csv_find_replace_column("1019 Reforest","1019 Reforestation Fund", "REPORT_LINE")
csv_find_replace_column("1021 Agric Loan","1021 Agricultural Loan Fund", "REPORT_LINE")
csv_find_replace_column("1024 Fish/Game","1024 Fish and Game Fund", "REPORT_LINE")
csv_find_replace_column("1026 Hwy Capitl","1026 Highways/Equipment Working Capital Fund", "REPORT_LINE")
csv_find_replace_column("1027 Int Airprt","1027 International Airport Revenue Fund", "REPORT_LINE")
csv_find_replace_column("1031 Sec Injury","1031 Second Injury Fund Reserve Account", "REPORT_LINE")
csv_find_replace_column("1034 Teach Ret","1034 Teachers Retirement System Fund", "REPORT_LINE")
csv_find_replace_column("1036 Cm Fish Ln","1036 Commercial Fishing Loan Fund", "REPORT_LINE")
csv_find_replace_column("1195 SnoMachReg","1195 Snow Machine Registration Receipts", "REPORT_LINE")
csv_find_replace_column("1037 GF/MH","1037 General Fund / Mental Health", "REPORT_LINE")
csv_find_replace_column("1038 UA/STF SVC","1038 U/A Student Tuition/Fees/Services", "REPORT_LINE")
csv_find_replace_column("1039 UA/ICR","1039 U/A Indirect Cost Recovery", "REPORT_LINE")
csv_find_replace_column("1040 Surety Fnd","1040 Real Estate Surety Fund", "REPORT_LINE")
csv_find_replace_column("1192 Mine Trust","1192 Mine Reclamation Trust Fund", "REPORT_LINE")
csv_find_replace_column("1042 Jud Retire","1042 Judicial Retirement System", "REPORT_LINE")
csv_find_replace_column("1044 Debt Ret","1044 AK Debt Retirement Fund", "REPORT_LINE")
csv_find_replace_column("1046 Stdnt Loan","1046 Student Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1048 Univ Rcpt","1048 University Restricted Receipts", "REPORT_LINE")
csv_find_replace_column("1050 PFD Fund","1050 Permanent Fund Dividend Fund", "REPORT_LINE")
csv_find_replace_column("1057 Small Bus","1057 Small Business Loan Fund", "REPORT_LINE")
csv_find_replace_column("1058 Trsm Loan","1058 Tourism Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1059 Corr. Ind.","1059 Correctional Industries Fund", "REPORT_LINE")
csv_find_replace_column("1060 OF(Pre'84)","1060 Other Funds (Pre-FY '84 Only)", "REPORT_LINE")
csv_find_replace_column("1061 CIP Rcpts","1061 Capital Improvement Project Receipts", "REPORT_LINE")
csv_find_replace_column("1063 NPR Fund","1063 National Petroleum Reserve Fund", "REPORT_LINE")
csv_find_replace_column("9003 Unkn DGF","9003 Unknown DGF Fund Source", "REPORT_LINE")
csv_find_replace_column("1067 Mining RLF","1067 Mining Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1068 Child Care","1068 Child Care Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1069 Hist Dist","1069 Historical District Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1070 Fish En Ln","1070 Fisheries Enhancement Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1071 Alt Energy","1071 Alternative Energy Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1072 Res Energy","1072 Residential Energy Conservation Loan Fund", "REPORT_LINE")
csv_find_replace_column("1074 Bulk Fuel","1074 Bulk Fuel Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1076 Marine Hwy","1076 Marine Highway System Fund", "REPORT_LINE")
csv_find_replace_column("1078 Sr Housing","1078 Senior Housing Loan Fund", "REPORT_LINE")
csv_find_replace_column("1081 Info Svc","1081 Information Services Fund", "REPORT_LINE")
csv_find_replace_column("1082 Vessel Rep","1082 Vessel Replacement Fund", "REPORT_LINE")
csv_find_replace_column("1086 SE Energy","1086 Southeast Energy Fund", "REPORT_LINE")
csv_find_replace_column("1088 UnInc Mtch","1088 Unincorporated Matching Grant Fund", "REPORT_LINE")
csv_find_replace_column("1089 Power Cost","1089 Power Cost Equalization Fund", "REPORT_LINE")
csv_find_replace_column("1090 4 Dam Pool","1090 Four Dam Pool Transfer Fund", "REPORT_LINE")
csv_find_replace_column("1091 GF/Desig","1091 General Funds - Designated", "REPORT_LINE")
csv_find_replace_column("1094 MHT Admin","1094 Mental Health Trust Administration", "REPORT_LINE")
csv_find_replace_column("1097 AETNA Res","1097 Group Health and Life Benefits Fund (AS 39.30.095)", "REPORT_LINE")
csv_find_replace_column("1098 ChildTrErn","1098 Children's Trust Earnings", "REPORT_LINE")
csv_find_replace_column("1099 ChildTrPrn","1099 Children's Trust Principal", "REPORT_LINE")
csv_find_replace_column("1100 ADWF","1100 Alaska Drinking Water Fund", "REPORT_LINE")
csv_find_replace_column("1103 AHFC Rcpts","1103 Alaska Housing Finance Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("-1 Unknown GF","-1 Unknown GF", "REPORT_LINE")
csv_find_replace_column("1102 AIDEA Rcpt","1102 Alaska Industrial Development & Export Authority Receipts", "REPORT_LINE")
csv_find_replace_column("1104 MBB Rcpts","1104 Alaska Municipal Bond Bank Receipts", "REPORT_LINE")
csv_find_replace_column("1105 PFund Rcpt","1105 Alaska Permanent Fund Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("1107 AEA Rcpts","1107 Alaska Energy Authority Corporate Receipts", "REPORT_LINE")
csv_find_replace_column("1108 Stat Desig","1108 Statutory Designated Program Receipts", "REPORT_LINE")
csv_find_replace_column("1110 APUC Rcpts","1110 Alaska Public Utility Commission", "REPORT_LINE")
csv_find_replace_column("1092 MHTAAR","1092 Mental Health Trust Authority Authorized Receipts", "REPORT_LINE")
csv_find_replace_column("9999 No specif.","9999 No specific fund source", "REPORT_LINE")
csv_find_replace_column("1114 EVOS Rest","1114 Exxon Valdez Oil Spill Restoration Fund", "REPORT_LINE")
csv_find_replace_column("1115 InT/BuEnIn","1115 International Trade and Business Endowment Income", "REPORT_LINE")
csv_find_replace_column("1119 Tobac Setl","1119 Tobacco Settlement", "REPORT_LINE")
csv_find_replace_column("1121 MultiFunds","1121 Multiple Funds pre FY94", "REPORT_LINE")
csv_find_replace_column("1122 LIC/PER/CT","1122 License/Permits/Certification Pre 89", "REPORT_LINE")
csv_find_replace_column("1123 Care/Trmnt","1123 Care and Treatment - FY88", "REPORT_LINE")
csv_find_replace_column("1125 APA Plant","1125 APA Plant Maintenance & Operation - FY88", "REPORT_LINE")
csv_find_replace_column("1129 Legal Recp","1129 Legal Settlement Receipts - FY88", "REPORT_LINE")
csv_find_replace_column("1130 Handcap Fn","1130 Handicapped Vendor Facility Fund - FY88", "REPORT_LINE")
csv_find_replace_column("1049 Trng Bldg","1049 Training and Building Fund", "REPORT_LINE")
csv_find_replace_column("1174 UA I/A","1174 UA Intra-Agency Transfers", "REPORT_LINE")
csv_find_replace_column("1132 Publ/Other","1132 Publications and Other Services - FY88", "REPORT_LINE")
csv_find_replace_column("1096 ILT Fund","1096 Investment Loss Trust Fund (DO NOT USE)", "REPORT_LINE")
csv_find_replace_column("1017 Ben Sys","1017 Benefits Systems Receipts", "REPORT_LINE")
csv_find_replace_column("1035 Vet Loan","1035 Veterans Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1045 Nat Guard","1045 National Guard & Naval Militia Retirement System", "REPORT_LINE")
csv_find_replace_column("1055 IA/OIL HAZ","1055 Interagency/Oil & Hazardous Waste", "REPORT_LINE")
csv_find_replace_column("1064 House Loan","1064 Housing Assistance Loan Fund", "REPORT_LINE")
csv_find_replace_column("1073 Pwr Dv RLF","1073 Power Development Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1084 Alyeska","1084 Alyeska Settlement Fund", "REPORT_LINE")
csv_find_replace_column("1095 Med Facil","1095 Medical Facilities Authority Fund", "REPORT_LINE")
csv_find_replace_column("1113 AHFC Bonds","1113 Alaska Housing Finance Corporation Bonds", "REPORT_LINE")
csv_find_replace_column("1118 Pioneers' ","1118 Pioneers' Homes Receipts", "REPORT_LINE")
csv_find_replace_column("1224 MariculRLF","1224 Mariculture Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1135 AMHS Dup","1135 Marine Highway Duplicated Expenditures", "REPORT_LINE")
csv_find_replace_column("1137 DComp IA","1137 Inactive-Deferred Compensation Inter Agency Receipts", "REPORT_LINE")
csv_find_replace_column("1229 AGDC-ISP","1229 AK Gasline Development Corporation In-state Pipeline Fund", "REPORT_LINE")
csv_find_replace_column("1138 Hlth I/A","1138 Inactive-Health Inter-Agency Receipts", "REPORT_LINE")
csv_find_replace_column("1141 RCA Rcpts","1141 RCA Receipts", "REPORT_LINE")
csv_find_replace_column("1142 RHIF/MM   ","1142 Retiree Health Ins Fund/Major Medical", "REPORT_LINE")
csv_find_replace_column("1143 RHIF/LTC","1143 Retiree Health Ins Fund/Long-Term Care Fund", "REPORT_LINE")
csv_find_replace_column("1144 CWF Bond","1144 Clean Water Fund Bond Receipts", "REPORT_LINE")
csv_find_replace_column("1145 AIPP Fund","1145 Art in Public Places Fund", "REPORT_LINE")
csv_find_replace_column("1023 FICA Acct","1023 FICA Administration Fund Account", "REPORT_LINE")
csv_find_replace_column("1109 Test Fish","1109 Test Fisheries Receipts", "REPORT_LINE")
csv_find_replace_column("-2 UnknwnOthr","-2 Unknown Other", "REPORT_LINE")
csv_find_replace_column("1150 ASLC Div","1150 ASLC Dividend", "REPORT_LINE")
csv_find_replace_column("1184 GOB DSFund","1184 General Obligation Bond Debt Service Fund", "REPORT_LINE")
csv_find_replace_column("1186 ASLC Bonds","1186 Alaska Student Loan Corporation Bond Proceeds", "REPORT_LINE")
csv_find_replace_column("2000 Bond Funds","2000 Bond Proceeds", "REPORT_LINE")
csv_find_replace_column("2001 Bonds MH","2001 Bond Proceeds Mental Health", "REPORT_LINE")
csv_find_replace_column("1218 146(c)code","1218 146(c)code", "REPORT_LINE")
csv_find_replace_column("1146 Fee Supp ","1146 Inactive-Fee Supported Increase", "REPORT_LINE")
csv_find_replace_column("1147 PublicBldg","1147 Public Building Fund", "REPORT_LINE")
csv_find_replace_column("1053 Invst Loss","1053 Investment Loss Trust Fund", "REPORT_LINE")
csv_find_replace_column("1139 AHFC Div","1139 AHFC Dividend", "REPORT_LINE")
csv_find_replace_column("1156 Rcpt Svcs","1156 Receipt Supported Services", "REPORT_LINE")
csv_find_replace_column("1152 AFSC Rcpts","1152 AK Fire Standards Council Receipts", "REPORT_LINE")
csv_find_replace_column("1153 State Land","1153 State Land Disposal Income Fund", "REPORT_LINE")
csv_find_replace_column("1157 Wrkrs Safe","1157 Workers Safety and Compensation Administration Account", "REPORT_LINE")
csv_find_replace_column("1158 Emp Pay","1158 Inactive Don't Use Employee Pay", "REPORT_LINE")
csv_find_replace_column("1154 Shore Fish","1154 Shore Fisheries Development Lease Program", "REPORT_LINE")
csv_find_replace_column("1159 DWF Bond","1159 Drinking Water Fund Bond Receipts", "REPORT_LINE")
csv_find_replace_column("1136 SBS IA","1136 Inactive-SBS Inter Agency Receipts", "REPORT_LINE")
csv_find_replace_column("1028 Pre90 PRGM","1028 Pre-FY90 Program Receipts", "REPORT_LINE")
csv_find_replace_column("1106 ASLC Rcpts","1106 Alaska Student Loan Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("1025 Sci/Tech","1025 Science & Technology Endowment Income", "REPORT_LINE")
csv_find_replace_column("1205 Ocn Rngr","1205 Berth Fees for the Ocean Ranger Program", "REPORT_LINE")
csv_find_replace_column("1124 Res Receip","1124 Resource Assessment Receipts - FY88", "REPORT_LINE")
csv_find_replace_column("1197 AK Cap Inc","1197 Alaska Capital Income Fund", "REPORT_LINE")
csv_find_replace_column("1203 WCBG Fund","1203 Workers' Compensation Benefits Guaranty Fund", "REPORT_LINE")
csv_find_replace_column("1127 User Fees","1127 User Fees - FY88", "REPORT_LINE")
csv_find_replace_column("1128 Child Sup","1128 Child Support Enforcement - FY88", "REPORT_LINE")
csv_find_replace_column("1999 No ID Fund","1999 Other Fund Source", "REPORT_LINE")
csv_find_replace_column("1131 RR Fund","1131 Alaska Railroad Revenue Fund - FY85, FY86, FY87", "REPORT_LINE")
csv_find_replace_column("1006 GF/MHTIA","1006 General Fund/Mental Health Trust", "REPORT_LINE")
csv_find_replace_column("1151 VoTech Ed","1151 Technical Vocational Education Program Account", "REPORT_LINE")
csv_find_replace_column("1160 M/C Protec","1160 Marine/Coastal Protection-Inactive", "REPORT_LINE")
csv_find_replace_column("1162 AOGCC Rcpt","1162 Alaska Oil & Gas Conservation Commission Rcpts", "REPORT_LINE")
csv_find_replace_column("1161 RRD Fund","1161 Renewable Resources Development Fund-Inactive", "REPORT_LINE")
csv_find_replace_column("1051 RuralEcDev","1051 Rural Economic Development Initiative Fund", "REPORT_LINE")
csv_find_replace_column("1222 REAA Fund","1222 Regional Educational Attendance Area School Fund", "REPORT_LINE")
csv_find_replace_column("1033 Surpl Prop","1033 Surplus Property Revolving Fund", "REPORT_LINE")
csv_find_replace_column("1164 RDIF","1164 Rural Development Initiative Fund", "REPORT_LINE")
csv_find_replace_column("1165 CBR/MH","1165 CBR/Mental Health", "REPORT_LINE")
csv_find_replace_column("1167 NTSC Bond","1167 Northern Tobacco Securitization Corporation Bonds", "REPORT_LINE")
csv_find_replace_column("1148 AATP Fund ","1148 Accelerated Alaska Transportation Projects Fund", "REPORT_LINE")
csv_find_replace_column("1043 Impact Aid","1043 Impact Aid for K-12 Schools", "REPORT_LINE")
csv_find_replace_column("1193 MaintGrant","1193 Major Maintenance Grant Fund", "REPORT_LINE")
csv_find_replace_column("1093 Clean Air","1093 Clean Air Protection Fund", "REPORT_LINE")
csv_find_replace_column("1194 F&G Nonded","1194 Fish and Game Nondedicated Receipts", "REPORT_LINE")
csv_find_replace_column("1170 SmBusEDRLF","1170 Small Business Economic Development Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1179 PFC ","1179 Passenger Facility Charges", "REPORT_LINE")
csv_find_replace_column("1126 Cont Reimb","1126 Contract Services Reimbursement - FY88", "REPORT_LINE")
csv_find_replace_column("1185 ElectionFd","1185 Election Fund (HAVA)", "REPORT_LINE")
csv_find_replace_column("1022 Corp Rcpts","1022 State Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("1077 Gifts/Grnt","1077 Gifts/Grants/Bequests", "REPORT_LINE")
csv_find_replace_column("1149 TAPL Fund","1149 Trans-Alaska Pipeline Liability Fund", "REPORT_LINE")
csv_find_replace_column("1163 COPs","1163 Certificates of Participation", "REPORT_LINE")
csv_find_replace_column("1032 Fish Fund","1032 Fishermen's Fund", "REPORT_LINE")
csv_find_replace_column("1177 ITB Endow","1177 International Trade and Business Endowment", "REPORT_LINE")
csv_find_replace_column("1181 Vets Endow","1181 Alaska Veterans' Memorial Endowment Fund", "REPORT_LINE")
csv_find_replace_column("1196 Master LOC","1196 Master Lease Line of Credit", "REPORT_LINE")
csv_find_replace_column("1182 Ed Cn/Mnt","1182 Educational and Museum Facility Design/Const/MajorMaint Fund", "REPORT_LINE")
csv_find_replace_column("1183 Trans Proj","1183 Transportation Project Fund", "REPORT_LINE")
csv_find_replace_column("1029 P/E Retire","1029 Public Employees Retirement System Fund", "REPORT_LINE")
csv_find_replace_column("1166 Vessel Com","1166 Commercial Passenger Vessel Environmental Compliance Fund", "REPORT_LINE")
csv_find_replace_column("1169 PCE Endow","1169 PCE Endowment Fund", "REPORT_LINE")
csv_find_replace_column("1173 Misc Earn","1173 Miscellaneous Earnings", "REPORT_LINE")
csv_find_replace_column("1225 CQuota RLF","1225 Community Quota Entity Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1178 tracking","1178 tracking code", "REPORT_LINE")
csv_find_replace_column("1112 IntAptCons","1112 International Airports Construction Fund", "REPORT_LINE")
csv_find_replace_column("1188 Fed Unrstr","1188 Federal Unrestricted Receipts", "REPORT_LINE")
csv_find_replace_column("1187 Fed MH","1187 Federal Mental Health", "REPORT_LINE")
csv_find_replace_column("1190 Adak Ops","1190 Adak Airport Operations ", "REPORT_LINE")
csv_find_replace_column("1191 DEED CIP","1191 DEED CIP Fund Equity Account", "REPORT_LINE")
csv_find_replace_column("1041 PF Earn Rs","1041 Permanent Fund Earnings Reserve Account", "REPORT_LINE")
csv_find_replace_column("1054 Empl Trng","1054 State Employment & Training Program", "REPORT_LINE")
csv_find_replace_column("1198 F&GRevBond","1198 Alaska Fish and Game Revenue Bond Redemption Fund", "REPORT_LINE")
csv_find_replace_column("1062 Power Proj","1062 Power Project Loan Fund", "REPORT_LINE")
csv_find_replace_column("1065 Rural Elec","1065 Rural Electrification Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1056 Elect Svc","1056 Electrical Service Extension Fund", "REPORT_LINE")
csv_find_replace_column("1075 Clean Wtr","1075 Alaska Clean Water Loan Fund", "REPORT_LINE")
csv_find_replace_column("1079 Storg Tank","1079 Underground Storage Tank Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1083 Educ Facil","1083 Education Facilities Maint & Construction", "REPORT_LINE")
csv_find_replace_column("1085 Rail InTie","1085 Railbelt Intertie Reserve Fund", "REPORT_LINE")
csv_find_replace_column("1087 Muni Match","1087 Municipal Matching Grant Fund", "REPORT_LINE")
csv_find_replace_column("1101 AERO Rcpts","1101 Alaska Aerospace Development Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("1212 Fed ARRA","1212 Federal Stimulus: ARRA 2009", "REPORT_LINE")
csv_find_replace_column("1052 Oil/Haz Fd","1052 Oil/Hazardous Prevention/Response Fund", "REPORT_LINE")
csv_find_replace_column("1117 VocRandSh","1117 Randolph Sheppard Small Business Fund", "REPORT_LINE")
csv_find_replace_column("1168 Tob Ed/Ces","1168 Tobacco Use Education and Cessation Fund", "REPORT_LINE")
csv_find_replace_column("1172 Bldg Safe","1172 Building Safety Account", "REPORT_LINE")
csv_find_replace_column("1176 Sci/T End","1176 Science and Technology Endowment Fund", "REPORT_LINE")
csv_find_replace_column("1011 Educ Trust","1011 Alaska Advance College Tuition Payment Fund", "REPORT_LINE")
csv_find_replace_column("1018 EVOSS","1018 Exxon Valdez Oil Spill Settlement", "REPORT_LINE")
csv_find_replace_column("1020 Grain Fund","1020 Grain Reserve Loan Fund", "REPORT_LINE")
csv_find_replace_column("1133 CSSD Reimb","1133 CSSD Administrative Cost Reimbursement", "REPORT_LINE")
csv_find_replace_column("1175 BLic&Corp","1175 Business License and Corporation Filing Fees and Taxes", "REPORT_LINE")
csv_find_replace_column("1199 SFEntAcct","1199 Alaska Sport Fishing Enterprise Account", "REPORT_LINE")
csv_find_replace_column("1219 Emrng Tech","1219 Emerging Energy Technology Fund", "REPORT_LINE")
csv_find_replace_column("1116 DisRlFd","1116 Disaster Relief Fund", "REPORT_LINE")
csv_find_replace_column("1140 AIDEA Div","1140 AIDEA Dividend", "REPORT_LINE")
csv_find_replace_column("1066 Pub School","1066 Public School Trust Fund", "REPORT_LINE")
csv_find_replace_column("1030 School Fnd","1030 School Fund (Cigarette Tax)", "REPORT_LINE")
csv_find_replace_column("1189 Sr Care","1189 Senior Care Fund", "REPORT_LINE")
csv_find_replace_column("1200 VehRntlTax","1200 Vehicle Rental Tax Receipts", "REPORT_LINE")
csv_find_replace_column("1201 CFEC Rcpts","1201 Commercial Fisheries Entry Commission Receipts", "REPORT_LINE")
csv_find_replace_column("1202 Anatomical","1202 Anatomical Gift Awareness Fund", "REPORT_LINE")
csv_find_replace_column("1155 Timber Rcp","1155 Timber Sale Receipts", "REPORT_LINE")
csv_find_replace_column("1207 Cr Shp Imp","1207 Regional Cruise Ship Impact Fund", "REPORT_LINE")
csv_find_replace_column("1208 BF Brdg LF","1208 Bulk Fuel Bridge Loan Fund", "REPORT_LINE")
csv_find_replace_column("1209 Capstone","1209 Alaska Capstone Avionics Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1210 Renew Ener","1210 Renewable Energy Grant Fund", "REPORT_LINE")
csv_find_replace_column("1206 CPV Tax","1206 Commercial Passenger Vessel Tax", "REPORT_LINE")
csv_find_replace_column("9000 Unkn UGF","9000 Unknown UGF Fund Source", "REPORT_LINE")
csv_find_replace_column("9001 Unknwn Fed","9001 Unknown Federal Fund Source", "REPORT_LINE")
csv_find_replace_column("9002 Unknwn Oth","9002 Unknown Other Fund Source", "REPORT_LINE")
csv_find_replace_column("1211 CSG Tax","1211 Cruise Ship Gambling Tax", "REPORT_LINE")
csv_find_replace_column("1171 PFD Crim","1171 Restorative Justice", "REPORT_LINE")
csv_find_replace_column("1216 Boat Rcpts","1216 Boat Registration Fees", "REPORT_LINE")
csv_find_replace_column("1215 UCR Rcpts","1215 Uniform Commercial Registration fees", "REPORT_LINE")
csv_find_replace_column("1214 WhitTunnel","1214 Whittier Tunnel Toll Receipts", "REPORT_LINE")
csv_find_replace_column("1217 NGF Earn","1217 NGF Earnings", "REPORT_LINE")
csv_find_replace_column("1009 Rev Bonds","1009 Revenue Bonds", "REPORT_LINE")
csv_find_replace_column("1220 Crime VCF","1220 Crime Victim Compensation Fund", "REPORT_LINE")
csv_find_replace_column("1258 CIF UGF","1258 UGF Deposits to the CIF", "REPORT_LINE")
csv_find_replace_column("1008 G/O Bonds","1008 General Obligation Bonds", "REPORT_LINE")
csv_find_replace_column("1221 Civil Legl","1221 Civil Legal Services Fund", "REPORT_LINE")
csv_find_replace_column("1001 CBR Fund","1001 Constitutional Budget Reserve Fund", "REPORT_LINE")
csv_find_replace_column("1223 CharterRLF","1223 Commercial Charter Fisheries RLF", "REPORT_LINE")
csv_find_replace_column("1080 Schl Const","1080 School Construction Fund", "REPORT_LINE")
csv_find_replace_column("1047 Title 20","1047 Title XX", "REPORT_LINE")
csv_find_replace_column("1120 MotorFuel ","1120 Motor Fuel Tax Increase", "REPORT_LINE")
csv_find_replace_column("1226 High Ed","1226 Alaska Higher Education Investment Fund", "REPORT_LINE")
csv_find_replace_column("1227 MicroRLF","1227 Alaska Microloan Revolving Loan Fund", "REPORT_LINE")
csv_find_replace_column("1111 FishFndInc","1111 Fishermans Fund Income", "REPORT_LINE")
csv_find_replace_column("1134 F&G CFP","1134 Fish and Game Criminal Fines and Penalties", "REPORT_LINE")
csv_find_replace_column("1213 AHCC Rcpts","1213 Alaska Housing Capital Corporation Receipts", "REPORT_LINE")
csv_find_replace_column("1180 Alcohol Fd","1180 Alcohol & Other Drug Abuse Treatment & Prevention Fund", "REPORT_LINE")
csv_find_replace_column("1228 UGFSequest","1228 UGF Associated with Sequestration", "REPORT_LINE")
csv_find_replace_column("1234 LicPlates","1234 License Plates", "REPORT_LINE")
csv_find_replace_column("1244 Rural Air","1244 Rural Airport Receipts", "REPORT_LINE")
csv_find_replace_column("1245 R Apt I/A","1245 Rural Airport Receipts I/A", "REPORT_LINE")
csv_find_replace_column("1239 AvFuel Tax","1239 Aviation Fuel Tax Revenue", "REPORT_LINE")
csv_find_replace_column("1275 Reapprop","1275 Reappropriation - Temporary to Match Leg Fin", "REPORT_LINE")


csv_find_replace_column(find, replace, column)
{
    global
    sql := 'ALTER TABLE %date_created%_%capital_scenario_272%_272 RENAME "' find '" TO "' replace '";`r`n'
    FileAppend(sql,"CAP NEW sql.txt")
}
